### ISSUE TITLE
Initialize Prometheus Server on AWS

### ISSUE THREAD

**Issue by theMultitude** [masa-finance/masa-oracle#301]
Prometheus will communicate with Consul to understand which nodes to scrape and house time-series information related to Protocol Nodes.

### Implementation

1. Using prometheus.yml:
```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'consul'
    consul_sd_configs:
      - server: '<CONSUL_SERVER_IP>:8500' <<-- using IP from one of the Consul servers from previous step
        services: []
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: '.*,prometheus,.*'
        action: keep
```
Create dockerfile:

```
FROM prom/prometheus
COPY prometheus.yml /etc/prometheus/prometheus.yml
```

2. Build the image and send to registry.  I'm not sure if we're using Dockerhub or another service at this point.
e.g. 
```
docker build -t dockerhub_username/prometheus:latest -f Dockerfile.prometheus .

docker push dockerhub_username/prometheus:latest
```

3. Allocate resources using Terraform
```
provider "aws" {
  region = "us-west-2" <<-- Adjust region
}

resource "aws_instance" "prometheus" {
  ami           = "ami-0c55b159cbfafe1f0" # Amazon Linux 2 AMI
  instance_type = "t2.micro"
  tags = {
    Name = "Prometheus"
  }

  user_data = <<-EOF
              #!/bin/bash
              echo "Starting Prometheus"
              docker run -d --name=prometheus -p 9090:9090 dockerhub_username/prometheus:latest
              EOF
}

output "prometheus_ip" {
  value = aws_instance.prometheus.public_ip
}
```
