### ISSUE TITLE
Add client docker specifications to Protocol Nodes

### ISSUE THREAD

**Issue by theMultitude** [masa-finance/masa-oracle#305]
Masa Nodes need to have their configurations changed to include Consul and Prometheus.  As a POC we will update the dockerfile used to build a protocol node to include Consul and Prometheus specifications.

Example file structure:
```
.
├── Dockerfile.consul
├── Dockerfile.prometheus
├── prometheus.yml
├── docker-compose.yml
└── consul
    └── config
        └── config.json
```

Dockerfiles:

`Dockerfile.consul`:
```
# Use the official Consul image as the base image
FROM consul:latest

# Expose the Consul ports
EXPOSE 8300 8301 8301/udp 8302 8302/udp 8500 8600 8600/udp

# Set the entrypoint to start the Consul agent
ENTRYPOINT ["consul", "agent", "-retry-join=<YOUR-CENTRAL-CONSUL-CLUSTER-IP>", "-data-dir=/consul/data", "-config-dir=/consul/config"]

# Copy needed configuration files
COPY config /consul/config
```

`Dockerfile.prometheus`:
```
# Use the official Prometheus image as the base image
FROM prom/prometheus:latest

# Expose the Prometheus port
EXPOSE 9090

# Set the entrypoint to start Prometheus
ENTRYPOINT ["prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
```

Prometheus configuration in `prometheus.yml`:
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'local'
    static_configs:
      - targets: ['localhost:9090']  # local Prometheus target

  # Add other local scrape targets as needed
```

`docker-compose.yml` example:

```
version: '3.8'

services:
  consul-agent:
    build:
      context: .
      dockerfile: Dockerfile.consul
    container_name: consul-agent
    volumes:
      - consul-data:/consul/data
      - ./consul/config:/consul/config
    networks:
      - analytics-network

  prometheus-agent:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus-agent
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - analytics-network

volumes:
  consul-data:
  prometheus-data:

networks:
  analytics-network:
    driver: bridge
```

Consul configuration in `config.json`:
```
{
  "datacenter": "dc1",  // Define the datacenter (optional, defaults to "dc1")
  "node_name": "node1",  // Unique name for the node (optional, autogenerated if not set)
  "advertise_addr": "192.168.1.1",  // Advertise address (optional, defaults to bind_addr if not set)
  "client_addr": "0.0.0.0",  // Client address (optional, defaults to "127.0.0.1")
  "retry_join": [  // Addresses to join the existing cluster
   "192.168.1.100",          // IP address of a Consul server
    OR
    "consul-server.example.com",  // DNS name of Consul server(s)
    OR
    "provider=aws tag_key=consul tag_value=prod"  // AWS tag for discovery
  ],
  "data_dir": "/var/lib/consul",  // Directory for state data (mandatory)
  "log_level": "INFO",  // Logging verbosity (optional, defaults to "INFO")
  "enable_syslog": true,  // Enable syslog (optional, defaults to false)
  "service": {  // Service definition, nodes can have multiple, based on functionality (optional)
    "name": "my-service", // worker, validator
    "tags": ["tag1", "tag2"], 
    "port": 8080,
    "check": {
      "http": "http://localhost:8080/health",
      "interval": "10s"
    }
  }
}
```
